apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: GKE production target
gke:
  cluster: projects/inductive-gift-456306-h4/locations/us-central1/clusters/java-kub-cluster-1
